# Generated by Django 4.2.1 on 2024-03-18 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en-US', 'English'), ('ja-JP', 'Japanese'), ('zh-CN', 'Chinese'), ('ko-KR', 'Korean')], default='en-US', max_length=10, verbose_name='대화 언어')),
                ('level', models.SmallIntegerField(choices=[(1, '초급'), (2, '고급')], default=1, verbose_name='레벨')),
                ('situation', models.CharField(max_length=100, verbose_name='상황')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
